###################################
#  SConstruct                     #
#                                 #
#  Builds solve                   #
###################################
### what to link ###
env = Environment()
link = env.Object(['solution.cpp'] + Glob('solution_*.cpp'))
env['LIBS'] = []
env['CXXFLAGS'] = ['-Wall']
### build ###
solve = env.Program('../solve', ['solve.cpp'] + link)
